//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_Salon.Database
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string MainImagePath { get; set; }
        public int DurationInSeconds { get; set; }
        public decimal Cost { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }

        public string CostWithDiscount 
        {
            get 
            {
                if (this.Discount > 0) 
                { 
                    var costWithDiscount = Convert.ToDouble(this.Cost) - Convert.ToDouble(this.Cost) * Convert.ToDouble(this.Discount / 100.00);
                    return costWithDiscount.ToString();
                }
                return this.Cost.ToString();
            }
        }
        public string ImgPath 
        {
            get 
            {
                var path = " pack://application:,,,/Resources/" + this.MainImagePath;
                return path;
            }
        }
        public string TimeInMinute
        {
            get 
            {
                var timeInMinute = DurationInSeconds / 60;
                return timeInMinute.ToString();
            }
        }
        private bool HasDiscount
        {
            get 
            { 
                return Discount > 0;
            }
        }
        private double OldCost
        {
            get 
            { 
                return Convert.ToDouble(this.Cost);
            }
        }

    }
}
